title: "Can's Blog"
description: "Just space for ranting really"
url: "www.caneldem.dev"
baseurl: ""
author: "Can Eldem"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

permalink: /:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - output/